### ISSUE TITLE
Group management recommendations for CFDE Epic 1

### ISSUE THREAD

**Issue by lliming** [nih-cfde/security#6]
We need a concise set of recommended practices for managing the DCC Reviewer groups in Globus for Epic 1. The groups will be used to control access to the DCC data for review in Epic 1. The CFDE Engagement Team is administering the groups, and need recommended practices for onboarding appropriate individuals to each group.

- How to identify the right identity for each person?
- Best practice for handling invitations?
- Specific instructions for invitees?
- How to delegate group management to an appropriate DCC representative?

**Comment by ACharbonneau** [comment]
In a conversation with @karlcz  yesterday, I hit a potential issue with our review plan and am looking for input. 

Within the most technical scope of epic 1, we don't have a problem, as none of the DCC humans overlap between DCC for our currently uploaded metadata. However, in our group of 14 DCCs, we do have PIs who are the main PIs of more than one DCC. 

I'm assuming it's not a problem to add a human to more than one of my DCC groups, I'm in all of them after all. But if I stay in all the groups, I honestly have no idea what I would expect to see on the review page. 

So, this will be an issue for the display, as it won't know which DCC data to show them by default, unless we make this one person log in with two different IDs, depending on the DCC they want to be from that day.


Here's my questions:

If I design a report display/workflow that allows for multiple report views, would it know about all the info simultaneously? Or would the user be switching between groups?


Are there any auth complications to this? For instance, with the "sign off" and knowing which DCC data is approved?

**Comment by lliming** [comment]
Is the "sign off" happening in the UI? (As opposed to them simply telling us via email or verbally that they approve.) I wasn't aware that was part of the plan.

**Comment by ACharbonneau** [comment]
So, we went with "no" for the sign off button in the UI.

at this exact moment, sign off is happening by me emailing people manually as an out of band thing.

 I think that the plan for epic 1 was to finish the implementation of having the sign off be able to happen in a github ticket the user was directed to from an email they get from doing an ingest? So there could be the same sort of back and forth discussion. Unless i'm misunderstanding @rpwagner 

so maybe the answer is that there's no auth issues?

**Comment by lliming** [comment]
> so maybe the answer is that there's no auth issues?

Sounds like that's true: no issues from the auth area with an individual belonging to more than one DCC review group. (Still sounds like it might complicate the UI, though.)

**Comment by karlcz** [comment]
Right, I think the authn/authz layer should be able to reflect that a
user has multiple privileges for multiple roles, and things like
reporting may need a UX to choose a narrower view if there is
ambiguity at the start.

In general, I think the UX should also strive to support a multi-role
view, i.e. show a broader compendium of information where
applicable. For example, that seems like a good top-level program
officer view of the world?

But, I would think that having a way for the user to choose the
narrower view is important for more focused user tasks, and it also
might be a stop-gap solution if there really isn't a feasible
multi-role view to offer at the start?

I would also add that if we are working with pre-release content in
the ingest process, there might be navigation to more narrowly-scoped
workspaces that have been prepared. This is a scenario where the
multi-role view is not possible, because you would have to choose which
draft workspace you wish to review, based on a single DCC datapackage
submission. There would not be a candidate build mixing the pre-release
content of multiple DCCs.

**Comment by lliming** [comment]
This is the document with the recommendations in it.

https://github.com/nih-cfde/security/blob/master/epic-1-groups/epic-1-groups.md
